# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rajmohan - Blog
name : Rajmohan Kathiresan
email: rajmohankathiresan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developing mobile application since its initial days of Mobile revolution 
  for all existed/existing/surviving platform such as iOS, Android (using Xamarin), Windows Phone 
  using various technology and framework.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rajkm.xyz" # the base hostname & protocol for your site
twitter_username: rajmohankathire
github_username:  rajmohankathiresan
linkedin_username: rajmohankathiresan
stack_of_username: 1423562/rajmohan-kathiresan
aboutme: rajmohankathiresan
blog_url: "/blog"

#Front Page
front_excerpt: "Software Developer, Techie, Fact Enthusiast"

avatar: yes
avatar_img_path: "https://avatars0.githubusercontent.com/u/2870046"

front_img: yes
front_img_path: "assets/coverphoto.jpg"

favicon_img: yes
favicon_img_path: "assets/favicon.png"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
theme: minima
